### ISSUE TITLE
android.content.ActivityNotFoundException

### ISSUE THREAD

**Issue by qsef1256** [BJ-Jeong/Capstone2022#9]
```
2022-06-13 07:53:29.096 6829-6829/com.example.capstone2022 E/AndroidRuntime: FATAL EXCEPTION: main
    Process: com.example.capstone2022, PID: 6829
    android.content.ActivityNotFoundException: Unable to find explicit activity class {com.example.capstone2022/com.example.capstone2022.MypageFragment}; have you declared this activity in your AndroidManifest.xml?
        at android.app.Instrumentation.checkStartActivityResult(Instrumentation.java:2085)
        at android.app.Instrumentation.execStartActivity(Instrumentation.java:1747)
        at android.app.Activity.startActivityForResult(Activity.java:5404)
        at androidx.activity.ComponentActivity.startActivityForResult(ComponentActivity.java:597)
        at android.app.Activity.startActivityForResult(Activity.java:5362)
        at androidx.activity.ComponentActivity.startActivityForResult(ComponentActivity.java:583)
        at android.app.Activity.startActivity(Activity.java:5748)
        at android.app.Activity.startActivity(Activity.java:5701)
        at com.example.capstone2022.MeMypage.lambda$onCreate$0$com-example-capstone2022-MeMypage(MeMypage.java:31)
        at com.example.capstone2022.MeMypage$$ExternalSyntheticLambda1.onClick(Unknown Source:2)
        at android.view.View.performClick(View.java:7441)
        at android.view.View.performClickInternal(View.java:7418)
        at android.view.View.access$3700(View.java:835)
        at android.view.View$PerformClick.run(View.java:28676)
        at android.os.Handler.handleCallback(Handler.java:938)
        at android.os.Handler.dispatchMessage(Handler.java:99)
        at android.os.Looper.loopOnce(Looper.java:201)
        at android.os.Looper.loop(Looper.java:288)
        at android.app.ActivityThread.main(ActivityThread.java:7839)
        at java.lang.reflect.Method.invoke(Native Method)
        at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:548)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1003)
```
마이 페이지에서 수정 후 뒤로 가기 누를 때 비정상 종료

**Comment by qsef1256** [comment]
혜원님 커밋 로그에 사용자 이름 제대로 안 뜨는데, 링크가 불가능하네요 확인해주세요
